Update

diff --git a/sh_Conan2/Debug_CMake_GC b/sh_Conan2/Debug_CMake_GC
--- a/sh_Conan2/Debug_CMake_GC
+++ b/sh_Conan2/Debug_CMake_GC
@@ -5,7 +5,7 @@ workspaceFolder=$1
 # program=$2
 
 echo -e "\e[1m--------- --------------------------- ---------"
-echo -e "--------- Generate | Terminal | Cmake ---------"
+echo -e "--------- Generate | -Debug- | Cmake ---------"
 echo -e "--------- --------------------------- ---------";
 echo -e "\e[100m \e[1m"
 echo -e "WorkSpace Directory: \e[0m"
@@ -24,16 +24,45 @@ echo ;
 
 cd $workspaceFolder
 
-### If the build folder does not exist, mkdir
-if [ ! -d "build" ]
+
+# if [ ! -d "build" ] ### Folder does NOT exist, mkdir
+if [ -d "build" ]; ### Folder does EXIST, mkdir
 then
-		mkdir -p -v "build"
-else
-		echo "build find it!"
+# 	echo "Building with Conan v2! // Debug"
+# 	conan install . --output-folder=build/Debug --build=missing --settings=build_type=Debug
+
+# else
+	# mkdir -p -v "build"
+	# conan install . --output-folder=build/Debug --build=missing ## Release
+	echo "build dir already exist!"
+	echo "Do you want to rebuild?"
+	
+	read answer
+
+	if [[ ("$answer" = "y") || ("$answer" = "Y") ]];
+	then
+		echo "Deleting build dir"
+		rm -rf build
+	else
+		echo "Exit!!!"
+		exit 
+	fi 
+
+fi
+
+echo "Building with Conan v2! // Debug"
+conan install . --output-folder=build/Debug --build=missing --settings=build_type=Debug
+
+if [ ! -d "build" ] ### Folder does NOT exist, mkdir
+then
+	echo "Error!!!"
+	echo "Building with conan has an error!!!"
+	
+	exit 
 fi
 
 echo
-cd build;
+cd build/Debug;
 pwd
 echo
 echo
@@ -46,13 +75,21 @@ echo
 # echo "+++++ Generated using Unix Makefiles +++++"
 
 
-### Ninja 
-cmake -G "Ninja" -DCMAKE_CXX_FLAGS="-fdiagnostics-color=always" -DCMAKE_C_FLAGS="-fdiagnostics-color=always" ..
+### Ninja Conan
+cmake -G "Ninja" -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake -DCMAKE_BUILD_TYPE=Debug ../..
 
+### Ninja
+# cmake -G "Ninja" -DCMAKE_CXX_FLAGS="-fdiagnostics-color=always" -DCMAKE_C_FLAGS="-fdiagnostics-color=always" ..
 # cmake -G "Ninja" -DCMAKE_CXX_FLAGS="-fdiagnostics-color=always" -DCMAKE_C_FLAGS="-fdiagnostics-color=always" -DCMAKE_EXPORT_COMPILE_COMMANDS=1..
 
 echo
-echo "+++++ Generated using Ninja +++++"
+echo "+++++ Generated using Ninja / Debug +++++"
+
+echo ; 
+echo ; 
+echo "+++++ +++++ Compiling +++++ +++++"
+
+cmake --build . --config Debug
 
 ##
 ###
